# Generated by Django 4.1 on 2022-08-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_route', models.CharField(max_length=200)),
                ('targets_rout', models.CharField(max_length=200)),
                ('model_type', models.CharField(max_length=100)),
            ],
        ),
    ]
